### ISSUE TITLE
Problems with debug mode

### ISSUE THREAD

**Issue by JordanLow** [JordanLow/ChessGame#15]

**Comment by ngjunsiang** [comment]
https://github.com/JordanLow/ChessGame/blob/28b9373359d54c154ad7a7ddc140caf9e7dbe491/chess.py#L26

This needs a `**kwargs` in arguments.
set `self.debug = kwargs.get('debug', False)`

Then you can just check the `self.debug` attribute to decide whether to print debug statements or not
