### ISSUE TITLE
Refactor `move()` for separation of concerns

### ISSUE THREAD

**Issue by ngjunsiang** [JordanLow/ChessGame#8]
chess.py [line 46](https://github.com/JordanLow/ChessGame/blob/c9b8701a34a6ce8b15a8eab14493fa16fc61665b/chess.py#L46)

## Issue

`move()` method does two things: update the location of the moved piece, and promote any pawns that reach the opposite end.

This makes it difficult to test the two features separately.

## Suggested resolution

Separate into two methods:

1. `move()` only updates the position of the selected piece
2. `promote()` (or a method name of your choice) checks for any pawns to be promoted. The user prompt (if any) to select piece to be promoted to should be done outside of this method.
3. The two methods should be called separately within `update()`

**Comment by JordanLow** [comment]
Solved in pull request #11
