### ISSUE TITLE
Implement get_coords() method for retrieving pieces with a specific colour and name

### ISSUE THREAD

**Issue by ngjunsiang** [JordanLow/ChessGame#9]
chess.py [lines 211-218](https://github.com/JordanLow/ChessGame/blob/c9b8701a34a6ce8b15a8eab14493fa16fc61665b/chess.py#L211)

## Issue

Searching for pieces with a specific colour/name is a process that is going to be needed for other features. It should be abstracted into its own method (as a companion method to `get_piece()`)

## Suggested resolution

1. Implement a `get_coords()` instance method for `Board` class.
2. This method should take in `colour` and `name` arguments, and return a list of coordinates for pieces with that `colour` and `name`
3. If no pieces are found, the method should return an empty list
4. Refactor `valid_move()` to use `get_coords()` to search for the `white king` and `black king`

**Comment by JordanLow** [comment]
Added in pull request #14
